### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by lucas42** [Financial-Times/asari#3]
In the FT, we have already have the string `github` [being used as a system code](https://biz-ops.in.ft.com/System/github).

Using the same string as a repository name, when the repository isn't the source code of that system can cause confusion in a few areas:
- We have automated tooling which identifies repos whose names are a system code and links them together in biz-ops
- People looking through a long list of repositories mightn't look up the README/description for every single one and may make some assumptions based on the name alone

Having a more descriptive name would be useful for people (and machines) not familiar with the specifics of this tool.

**Comment by lucas42** [comment]
Still causing an issue in biz-ops: https://biz-ops.in.ft.com/Repository/github%3AFinancial-Times%2Fgithub

**Comment by adambraimbridge** [comment]
![image](https://user-images.githubusercontent.com/224547/57675693-8ee35080-761a-11e9-89b0-ea64c084cb1f.png)

**Comment by adambraimbridge** [comment]
Renamed to `ika`

**Comment by adambraimbridge** [comment]
npmjs.com/package/ika is not available, but npmjs.com/package/asari is.

**Comment by adambraimbridge** [comment]
https://www.npmjs.com/package/asari
