### ISSUE TITLE
Add GitHub personal access token instructions to README

### ISSUE THREAD

**Issue by simonplend** [Financial-Times/asari#42]
There used to be documentation in the `README` for this project about GitHub personal access tokens. It went away [here](https://github.com/Financial-Times/github/commit/28c88ac5aa2d13356dcbde806b994062a8978f3a?diff=split#diff-04c6e90faac2675aa89e2176d2eec7d8L46). I agree that we shouldn't be linking to private internal documentation that non-FT folk can't access (which it was), but we should have _something_ in the `README` about GitHub personal tokens.

- [ ] What scope(s) does the GitHub personal access token require when it's being created?
- [ ] Can we add a link to help people create a new GitHub personal access token?

**Comment by simonplend** [comment]
Add details based on https://github.com/Financial-Times/github/pull/39

**Comment by sjparkinson** [comment]
> What scope(s) does the GitHub personal access token require when it's being created?

This is definitely going to change as more and more API endpoints are supported but for issues, pull requests and projects I think you need the full blown `repo` scope.

For org level projects you also need the `write:org` scope.
