### ISSUE TITLE
Add an .npmignore to this project

### ISSUE THREAD

**Issue by simonplend** [Financial-Times/asari#45]
The published package doesn't need to contain tests or any of the various config files.

See: https://circleci.com/gh/Financial-Times/github/170

Setting up an `.npmignore` for this project would be good learning to inform https://github.com/Financial-Times/next-transformations/issues/3.

**Comment by simonplend** [comment]
@adambraimbridge This has just been marked stale, but I reckon it's still worth considering as everything (tests, test results, dotfiles etc.) is currently getting bundled up and shipped to npm when `ika` is published as a package.

**Comment by adambraimbridge** [comment]
✅https://www.npmjs.com/package/asari
